### ISSUE TITLE
Playbar scrolling doesn't always work in streaming visualizer

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#11]
When dragging playbar to specific point in time for playback the streaming visualizer occasionally doesn't load the pointcloud from the `DataLoader` into the main execution thread for visualization.

**Comment by vrajur-nd** [comment]
Update: Fixed this issue in branch `truth-visualization` with the refactor of the animation timeline. Will close once that branch is merged in

**Comment by calistenson** [comment]
@vrajur-nd is this issue closable now? Seems like I still see it a lot...
