### ISSUE TITLE
Merge upstream changes

### ISSUE THREAD

**Issue by bcasselsND** [NextDroid/potree#117]
There are a bunch of upstream changes. The main one I want is that they have updated everything to work with the latest gulp. The older version causes lots of problems for me.

**Comment by bcasselsND** [comment]
The reason for starting this is that our version of potree was pinned to an older version of gulp, but other changes required updating that version. I had tried and failed to do update gulp, a few months ago.

I noticed that the upstream version uses current gulp. So I started merging upstream changes into our develop. My recent PRs, #125 and #127, updated us to current gulp. So this unblocks our develop branch.

So this issue can go into backlog, for a bit. We should get upstream changes, soon-ish, but for now we should merge our recent changes and fix current bugs.

**Comment by dgandhiAM** [comment]
Minimal set of changes complete.  Closing this issue and using #130 to continue tracking.
