### ISSUE TITLE
Veritas Application on Ubuntu 18/04

### ISSUE THREAD

**Issue by jstrinkaND** [NextDroid/potree#124]

**Comment by bcasselsND** [comment]
@jstrinkaND  I assume this is either supposed to be referring to potree, or it's in the wrong repo?

**Comment by jstrinkaND** [comment]
@bcasselsND This is in the wrong Repo. The ticket refers to getting veritas to run on Ubuntu 18.04

**Comment by bcasselsND** [comment]
VeritasApp has been running on AWS Ubuntu 20.04 servers for a while now.
