### ISSUE TITLE
Saving 3D cuboids in potree

### ISSUE THREAD

**Issue by arjunskND** [NextDroid/potree#145]
Reviving `Label and Download` button? What was this button doing? Is there any other way of downloading 3D cuboids?

**Comment by bcasselsND** [comment]
It looks to me as though this is supposed to be part of a different "app".
`data-labeling/data-labeling.html` Or maybe `data-labeling/data-labeling2.html`.

I don't know whether it can be folded into the main potree app `demo/radar.html`, or it should remain separate. You'll have to tell me what this thing is, and how you want to use it. If it should remain separate, I'll figure out how to keep this `Label and Download` thing from showing up when it shouldn't.
