### ISSUE TITLE
REM control point data takes > 15 mins to load

### ISSUE THREAD

**Issue by dgandhiAM** [NextDroid/potree#146]
In potree, datasets containing REM control points don't load the control point overlay for a very long time.

Prior to loading (~ 15 mins!):
![image.png](https://images.zenhubusercontent.com/5a95af9a4b5806bc2bc8a285/b2b019b8-82ba-4760-97a7-73764cc69b8d)

After load, it appears correctly as:
![image.png](https://images.zenhubusercontent.com/5a95af9a4b5806bc2bc8a285/6ad1cee4-2805-45e3-8889-cf2c0a5c6d18)

The associated .fb completes very early in the process (prior to the point cloud downloads):
`veritas-aptiv-2019-02-11/Data/REM-Lane1-Run1_2019-08-01¶002/3_Assessments/control_point_3_rtk_relative.fb`
![image.png](https://images.zenhubusercontent.com/5a95af9a4b5806bc2bc8a285/47d53376-07f2-427c-9d85-cd39ecc3c215)

After the REM points load, CPU utilization spikes to 100%:
![image.png](https://images.zenhubusercontent.com/5a95af9a4b5806bc2bc8a285/1dbc06d8-0f0d-4d1c-9508-496fc983265e)

**Comment by NickRizzo-droid** [comment]
I'm seeing the REM control points immediately upon load clumped up in the beginning
![image.png](https://images.zenhubusercontent.com/5e1de5b14e13e7ce0433a3fb/34263b8a-bac1-4279-ad74-f5e3a38be762)

As soon as I start playing, the points disappear
![image.png](https://images.zenhubusercontent.com/5e1de5b14e13e7ce0433a3fb/c0378a50-78a9-4e5d-9004-a002302b79ac)

**Comment by NickRizzo-droid** [comment]
## Investigation

- I checked timestamps of REM control points (which does seem to be happening in the beginning) and it looks like they are all there from timestamp 0-1302.07834649086)
    - Perhaps they are not getting loaded into the viewer correctly

**Comment by NickRizzo-droid** [comment]
## Reproducible temp fix
- related to #149 
    - > tracks don't appear after selected until time window is adjusted (need to refresh it or change both sides of the time-window)
- when running off develop (commit [bf33578f975f854087a7a3435c8abd6d273881fd]( https://github.com/NextDroid/potree/commit/bf33578f975f854087a7a3435c8abd6d273881fd)) the points showed up in the beginining, but would disappear when `Play` was clicked. If I refreshed the time window, the points showed up again and behaved normally

## Going Forward

- going to track down why the time window refreshing fixes the issue and do that on load

**Comment by NickRizzo-droid** [comment]
## Current progress 
- almost done
- need fix to limit number of points shown on load to match the window

#### on load
![image.png](https://images.zenhubusercontent.com/5e1de5b14e13e7ce0433a3fb/c04d89d7-a008-423d-ba92-2590f98620e7)

#### on play
(notice how rem points get limited to only 3)
![image.png](https://images.zenhubusercontent.com/5e1de5b14e13e7ce0433a3fb/9159a991-2109-491c-9e48-468ad943feea)
