### ISSUE TITLE
Object tracks take a long time to show up

### ISSUE THREAD

**Issue by NickRizzo-droid** [NextDroid/potree#149]
Based on @bcasselsND's observations
- should appear as red boxes around vehicle 
- sample dataset: `veritas-gm-2019-03-07/Data/GT004_4709-2¶002/2_Truth /tracks.fb` 
     - ~12s into it
     - bucket: `veritas-gm-2019-03-07` (might have to add gm-data-access permissions)
     - dataset name: `GT004_4709-2`
- Probably because progress bar tries to update for every entry so pauses accumulate
- might be addressed already by doing the update every hundredth or thousandth time.
- tracks don't appear after selected until time window is adjusted (need to refresh it or change both sides of the time-window)

**Comment by NickRizzo-droid** [comment]
#### Currently Seeing
(this is off [develop](https://github.com/NextDroid/potree/commit/7b8cad3dcf36cf247044ab02f50fb21788868180))
- tracking other objects, but not our car
![image.png](https://images.zenhubusercontent.com/5e1de5b14e13e7ce0433a3fb/176b17f6-3f7b-4f12-be6d-b6962f38fcb0)

**Comment by NickRizzo-droid** [comment]
#### Investigation
- this appears to be a symptom of #152
     - using print outs, you can see that the track data is being imported, loaded, and parsed **after** the loading bar disappears
     - once done loading, tracking boxes immediately become visible
     -  probably fixing issue #152 should this as track data would be loaded in prior to being able to start

**Comment by arjunskND** [comment]
Tested: `UNKNOWN_SLED_UNKNOWN_UNKNOWN_UNKNOWN_2020_05_22_19_44_39_UNKNOWN`

**Comment by arjunskND** [comment]
Can close, tracking loading times in
