### ISSUE TITLE
Unexpected Visualization Crash during Normal  Usage

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#15]
Visualization can crash after running for a period of time: [Log file](https://www.dropbox.com/home/NextDroid%20Team%20Folder/1_projects/18xx-nxd-veritas/08_sandbox/Vinay/Logs/Visualization)

Potree Visualization Commit: https://github.com/NextDroid/potree/commit/2ee13dbbadc5c1893be1801e7d1243ea4c1fd746

Context: 
- Running in Chrome `Version 71.0.3578.98 (Official Build) (64-bit)`
- Gaps were loaded
- Detections were loaded
- Crashed during normal interactions ("Aww snap")
- Visualization was not playing during crash
- Crash occurred after being open for somewhere between 10-20 min

**Comment by vrajur-nd** [comment]
This is still an issue, and we believe that it is tied to memory usage within potree.

There are a few known upstream issues referencing a memory leak in the visualization:
 - [upstream issue #222](https://github.com/potree/potree/issues/222)
 - [upstream issue #239](https://github.com/potree/potree/issues/239)
 - [upstream issue #235](https://github.com/potree/potree/issues/235)
 - potential solution (with PR): [upstream issue #628](https://github.com/potree/potree/issues/628)

Also see #29 for information about recent updated versions of chrome that seem to enforce stricter memory allocation limits.

**Comment by calistenson** [comment]
@vrajur-nd would it be worth having a design/arch discussion about how to incorporate potential solutions to this?
