### ISSUE TITLE
Add dual plus confidence support to potree

### ISSUE THREAD

**Issue by JKlimovND** [NextDroid/potree#151]
- Once changes have been made to potree converter, allow visualization of DPC attributes in potree
- Color by confidence, dual attributes
- Filter for only dual attributes, recommended drops, etc.

**Comment by JKlimovND** [comment]
Integration with measurement tool:

![Screenshot from 2020-06-25 10-33-48.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/85c14d1e-95e7-490a-b74c-fa2d49f9d31a)

**Comment by JKlimovND** [comment]
Current goals:

- Filter points based on attributes like Retro Ghost
- Integrate DPC with the composite view
- Different attributes visible for developers vs. users

**Comment by JKlimovND** [comment]
Dual distance (pointcloud highlight mode):
![Screenshot from 2020-06-29 08-24-30.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/cfe6c62c-3de3-44eb-a19a-0bde157870bf)

VeloView (which includes confidence as point data):
![Screenshot from 2020-06-29 08-25-21.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/39199e77-69f2-4bd2-bf6a-1678c49f5123)

Dual reflectivity:
![Screenshot from 2020-06-29 08-26-42.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/cd1f5186-286a-492e-bf6e-6525e584187c)

VeloView:
![Screenshot from 2020-06-29 08-27-06.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/37f14cdc-f21d-4eff-9b2e-f5c90334c0bb)

Confidence:
![Screenshot from 2020-06-29 08-27-33.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/3b6e6280-42cd-4861-9b91-ddfbefeda62b)

Dual distance (aggregate):
![Screenshot from 2020-06-29 08-24-58.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/3526cb0a-4f47-4f3d-8726-5e0b1cb22122)

Dual reflectivity (aggregate):
![Screenshot from 2020-06-29 08-26-21.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/87b6cd57-62c2-4ded-ba02-b02cdbedbb43)

**Comment by JKlimovND** [comment]
Composite view looking at dual reflectivity and confidence:
![Screenshot from 2020-06-29 09-39-12.png](https://images.zenhubusercontent.com/5e5977e6bf668337b28d0db1/3a5c1a11-dab6-42f7-8fb3-9663df5108ef)

**Comment by JKlimovND** [comment]
> OpenGL mandates implementations offer a minimum of 16 4-component vertex attributes. Therefore an index of 16 is not guaranteed to be supported by all implementations; see GL_MAX_VERTEX_ATTRIBS for more details.

> The maximum number of attribute locations is limited by the graphics hardware. You can retrieve the maximum supported number of vertex attributes with glGetIntegerv(GL_MAX_VERTEX_ATTRIBS, &n).

https://stackoverflow.com/questions/18543720/glsl-instancing-max-number-of-inputs-for-vertex-data
https://www.opengl.org/sdk/docs/tutorials/ClockworkCoders/attributes.php

**Comment by arjunskND** [comment]
Jesse's prior work has been merged in. Filtering the point cloud based on recommended drops for example is yet to completed.

**Comment by arjunskND** [comment]
@jallen-NextDroid , keep this in your radar. We can discuss at retro; @dgandhiAM and I think this is a fairly important issue to fix..
