### ISSUE TITLE
Annotating Lanes: Close the loop 

### ISSUE THREAD

**Issue by arjunskND** [NextDroid/potree#167]

**Comment by nmhaddadND** [comment]
We have decided to use AWS Lambda to update our lanes files after annotating in potree. This will allow us to directly update lanes files on S3 in real time.

We will write directly to S3 from the Lambda function. Lambda will also get versioned schema files from the directory of the dataset being updated.

Updating lanes will overwrite the previous version.

**Comment by nmhaddadND** [comment]
Lambda function is written and works. Will need to create multiple versions for us to use in the future. I am having trouble calling the function from potree due to permissions issues.
