### ISSUE TITLE
Merge upsteam potree with our fork

### ISSUE THREAD

**Issue by nmhaddadND** [NextDroid/potree#189]
We will need to do an upsteam merge with potree at some point in the next few weeks so that we do not get too far behind.

**Comment by dgandhiAM** [comment]
@nmhaddadND Assess impact of upstream merge to determine what we're missing if we delay merge.  Update this issue and then push to backlog, and we'll discuss path forward.

**Comment by nmhaddadND** [comment]
What's changed:
- Support for JSON5 (now used to store project files)
- classifier for identifying buildings, vegetation, ground, etc. (no road)
- VR controls
- More measurement tools and navigation tools
- Fix GPU memory leaks
- Zoom can increase and decrease more
- 360 view feature (and associated bug fixes)
- Bug fixes to double clicking
- Removed matrix inversion errors
- Switch to DataView from CustomVIew (faster)
- Fix measuring tool errors

@arjunskND @bcasselsND @dgandhiAM

**Comment by bcasselsND** [comment]
Memory leak has been a problem for us.

**Comment by nmhaddadND** [comment]
close as duplicate Veritas#497
