### ISSUE TITLE
Streaming Visualization and Potree Integration

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#2]
The streaming visualization currently creates and renders a pointcloud using a generic Three.js `Object3D`, and only using Potree's `Viewer` object for managing the scene, cameras and lighting. It would be useful to more closely integrate the streaming visualization with the remainder of Potree's tools including measurements, clipping, coloring, etc. 

**Current status as of 09-27-2018:**
the streaming visualization in `streaming-dev-potree-integration` currently allows a point cloud to be streamed into the root node of a `PointCloudOctree` object, enabling clipping and coloring. Selection of individual points in the point cloud using the mouse is not-functional which prohibits things like measurements and certain navigation controls (e.g. Earth Control). The issue as far as I can tell is in the`PointCloudOctree.pick()` function, which rerenders the current pointcloud (in a hidden view) using `pickMaterial` and uses raycasting to select the closest point to the mouse and pull its attributes (e.g. position, index, gpsTime, etc...). Looking at the debug console, I can see that points do get rendered and that raycasting returns a point - however the attributes pulled from that point are invalid (which is why clicking a point puts it's location at the base location of the current octree node). When picking back up on this, look at the `pick` function in `PointCloudOctree.js` starting at line 605.

**Comment by calistenson** [comment]
@vrajur-nd where's this issue now? Can you give us an update tomorrow?

**Comment by vrajur-nd** [comment]
No updates on this since my previous comment. Closing this since we won't really get to it anytime soon I'd say.
