### ISSUE TITLE
AWS Lambda: UpdateLanes Cache Fix

### ISSUE THREAD

**Issue by nmhaddadND** [NextDroid/potree#204]
We need to update `lanes.fb` to the most recent file on S3 whenever we switch over to truth lanes from annotation mode. What's happening now does not display the most updated lanes all the time and is a bug.

**Comment by nmhaddadND** [comment]
@jterranovaND

**Comment by nmhaddadND** [comment]
@jterranovaND look into how long it takes for S3 to update all file locations

**Comment by jterranovaND** [comment]
@nmhaddadND , is the write in question coming from the call to `write_buffer_to_s3(s3, bucket, name, builder)` ?

**Comment by nmhaddadND** [comment]
@jterranovaND yes, it writes from the Lambda function.

**Comment by jterranovaND** [comment]
UpdateLanes is working end-to-end.  It is still slow but it does complete in about 2 mins for larger datasets.
