### ISSUE TITLE
AWS Lambda: Get the right schema

### ISSUE THREAD

**Issue by nmhaddadND** [NextDroid/potree#205]
We want to be able to load schemas from datasets into the temporary file system on AWS Lambda. So far, this has been pretty hard to do, and right now, we are using a single Lambda Layer that contains the files we need. We will maintain that layer as a backup, but we will need to fix this issue at some point to handle versioning.

**Comment by nmhaddadND** [comment]
@jterranovaND check to see if UpdateLanes lambda function is a viable solution. If it is, then all you need to do is import a python module from a given S3 bucket and object, and import it into the lambda runtime.

**Comment by jterranovaND** [comment]
We are planning moving updatelane processing in to the browser, so we'll need to convert the python code to js.  Closing.
