### ISSUE TITLE
Error loading calibration file

### ISSUE THREAD

**Issue by bcasselsND** [NextDroid/potree#208]
On test.vts.nextdroid.com, Aptiv bucket, 2018_SLED_GT104_UNKNOWN_EXPEDITION_2020_07_17_20_06_20_FordTestConfirmation3
Trying to read "metadata" calType
calFile
``` {extrinsics: {…}, nominal: null, metadata: null}
extrinsics: {objectName: "Data/2018_SLED_GT104_UNKNOWN_EXPEDITION_2020_07_17…0_FordTestConfirmation3¶004/7_Cals/extrinsics.txt"}
metadata: null
nominal: null
__proto__: Object
```
```
dev.viz.nextdroid.com/demo/calibrationManager.js:239 Error loading calibration file: nominal TypeError: Cannot read property 'objectName' of null
    at loadCalibrationFile (dev.viz.nextdroid.com/demo/calibrationManager.js:219)
    at dev.viz.nextdroid.com/demo/loaderHelper.js:163
    at async loadRtkCallback (dev.viz.nextdroid.com/demo/rtkLoader.js:140)
```

**Comment by midnight-dev** [comment]
Check L#219 of calibrationManager.js. It's having trouble finding the file derived from the calibration files & calibration type passed in. If it exists in the bucket, the key isn't matching well. I'd separate the S3 call in its own try/catch so it's easier to spot file issues vs parsing errors.

May or may not be a problem depending on how well Unicode is handled, but there's a literal paragraph symbol ¶ in the object name.
