### ISSUE TITLE
Debug potree cuboids

### ISSUE THREAD

**Issue by SantoshReddyND** [NextDroid/potree#215]
potree labelling cuboids stopped working.

1) Last cuboid labelled overwrites the previously labelled data.
2) json data and json filename interchanged.

Steps to reproduce:

1) In potree, under the `clipping` tool bar select `Volume Clip` and drag and drop the cuboid on a road surface.
2) Assign `label` and `metaData` to the cuboid.
3) Download json file by clicking on the `JSON` from `Labels` toolbar.

**Comment by nmhaddadND** [comment]
@jallen-NextDroid talk to @SantoshReddyND to figure out what to do next
