### ISSUE TITLE
Have good default settings

### ISSUE THREAD

**Issue by bcasselsND** [NextDroid/potree#243]
The potree default settings do not give good visualizations. @jstrinkaND has figured out good initial settings, for Velodyne 64, and 128 (different settings for each).

Set things up so users get those settings by default.

Maybe allow them to tweak settings, and save them per user. (Maybe split this off as a separate task.)

Let's have potree make a good first impression.  ;-)

**Comment by dgandhiAM** [comment]
Duplicate... closing.
