### ISSUE TITLE
Efficient visualization gap data (Example code delete in PR #23)

### ISSUE THREAD

**Issue by calistenson** [NextDroid/potree#25]
Radar features todo.... (fill in goal of code below)

// let gapShaderMaterial = shaderMaterial.clone();
	// gapShaderMaterial.uniforms.color.value = new THREE.Color(0x0000ff);		// gapShaderMaterial.uniforms.color.value = new THREE.Color(0x0000ff);
	// loadGaps(s3, bucket, name, gapShaderMaterial, animationEngine, (gapGeometries) => {		// loadGaps(s3, bucket, name, gapShaderMaterial, animationEngine, (gapGeometries) => {
	//		//
	// 	// TODO TESTING -- REMOVE		// 	// TODO TESTING -- REMOVE
	// 	// debugger;		// 	// debugger;
	// 	for (let ii=0, len=gapGeometries.left.length; ii<len; ii++) {		// 	for (let ii=0, len=gapGeometries.left.length; ii<len; ii++) {
	// 		// if (ii < 1000) {		// 		// if (ii < 1000) {
	// 			viewer.scene.scene.add(gapGeometries.left[ii]);		// 			viewer.scene.scene.add(gapGeometries.left[ii]);
	// 		// }		// 		// }
	// 		animationEngine.tweenTargets.push((gpsTime) => {		// 		animationEngine.tweenTargets.push((gpsTime) => {
	// 			let currentTime = gpsTime - animationEngine.tstart;		// 			let currentTime = gpsTime - animationEngine.tstart;
	// 			gapShaderMaterial.uniforms.minGpsTime.value = currentTime - 0.05;		// 			gapShaderMaterial.uniforms.minGpsTime.value = currentTime - 0.05;
	// 			gapShaderMaterial.uniforms.maxGpsTime.value = currentTime + 0.05;		// 			gapShaderMaterial.uniforms.maxGpsTime.value = currentTime + 0.05;
	// 		});		// 		});
	// 	}		// 	}
	// });		// });
// TODO TILL HERE	// TODO TILL HERE

**Comment by vrajur-nd** [comment]
This code was an attempt at improving the way that vehicle gaps are visualized (removing visual artifacts and reducing data size in memory). Commented out because it is still in development.
