### ISSUE TITLE
Data loaders run out of order

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#28]
In radar.html the data loaders do not run in the intended order. I used async-await syntax to try and force the asynchronous data loaders to run in a particular order (namely the rtk data must be loaded in order to set the time range and properly initialize animationEngine before any other data source is loaded), however, it appears that this does not always work as intended.

Running the dataset 04_16_TDP2_control_45_b we observed that tracks were loaded before the rtk data was loaded, and thus the track timestamps were not properly initialized.

Need to understand javascript asynchronous processes better.

**Comment by calistenson** [comment]
@vrajur-nd is this still an open issue? I can take a look...

**Comment by vrajur-nd** [comment]
@calistenson  Sorry I didn't realize there was activity on this...yeah it is still an open issue, but I told Arjun I'd take a look, since he prob needs it by tomorrow and I think I have an idea of how to deal with this. I'll put you on the PR though

**Comment by calistenson** [comment]
@vrajur-nd sounds good.

**Comment by vrajur-nd** [comment]
closed.
