### ISSUE TITLE
Streaming Player does not run on newer versions of chrome

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#29]
Streaming player is currently unable to render segments (~100 MB) of point cloud data in newer versions of chrome (this issue has been confirmed on Chrome version 73). The only way to visualize data has been to reduce the size of the segment that is buffered into memory to around 10 MB but this is typically too small a segment of data to be useful, so a solution needs to be found in order to be compatible with current/future versions of chrome. For reference, version 67 of chrome does not have this issue.

**Comment by calistenson** [comment]
@vrajur-nd is this still an issue? Any investigation into solutions to fixing it or others fixing it?

**Comment by calistenson** [comment]
@vrajur-nd do we wanna write up and epic for the backlog?
