### ISSUE TITLE
Make RTK Calibration Parameters Adjustable

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#3]
We need a way to interactively adjust the calibration parameters for the SLED, including Velodyne --> RTK Extrinsics and RTK--> Vehicle Extrinsics. 

To Do:
- [x] Refactor hardcoded/implicit calibration values
- [x] Double check calibration is being applied properly 
- [x] Double check interpolation (need to visualize on data that doesn't contain rotational blurring, e.g. from raw pcap file)
- [x] Move visualization from rtk frame to vehicle frame (apply calibrations to rtk, radar data)
- [x] Create GUI for adjusting calibration parameters
- [x] Support exporting of calibration parameters (e.g. to csv for example)
- [ ] Handle loading of calibration file from server

**Comment by calistenson** [comment]
@vrajur-nd is everything described in this ticket complete? I have an epic on the veritasApplication side for our front end changes that will allow asset management and user input calibrations for us to feed the files into AWS: https://app.zenhub.com/workspaces/veritas-5b9aa680dfeccd3433cd6f62/issues/nextdroid/potreeconverter/5. Feel free to add any tickets you think the app side needs for calibrations there.

**Comment by vrajur-nd** [comment]
Pretty much complete. The last bullet point (loading from server) is not a worthwhile investment of time, so I'm going to call this ticket closed.
