### ISSUE TITLE
Data Loaders use a large amount of memory

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#30]
Data loaders (such as `radarLoader.js` and `detectionLoader.js`, etc...) seem to use a lot more memory than would be expected. This limits the amount of data that can be loaded into the visualization and crashes the page if the browser memory limits are exceeded. We need to figure out a way to reduce the memory footprint from loading these various data. 

Note: @bcasselsND @dgandhiAM Part of the issue right now is that all the data gets loaded and stored in memory at the start, which doesn't work for large datasets. A proper scalable solution would likely require streaming the data from S3, however, I am not currently sure whether the S3 api supports this functionality or if it would allow you to jump around within a file. If we wanted to do this there would also need to be development to setup some type of streaming manager as well.

**Comment by bcasselsND** [comment]
S3 does support this. I'll point you at the appropriate API, when I'm in
front of a computer.

**Comment by calistenson** [comment]
@bcasselsND can you post the api mentioned in this ticket?

@vrajur-nd how persistent is this problem?

**Comment by bcasselsND** [comment]
You can use the `Range` parameter to `getObject`, to start anywhere and get any length.

**Comment by calistenson** [comment]
@bcasselsND the range parameter on what exactly? Ideally we'd add commentary to our tickets that people without context could understand...

**Comment by bcasselsND** [comment]
[AWS S3 getObject API](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property)

**Comment by calistenson** [comment]
Seems like we could consider using an npm data stream: https://www.npmjs.com/package/event-stream

**Comment by bcasselsND** [comment]
The data loader needs to get data to the browser. Will npm data streams work there? Or are they a node-only thing?

**Comment by bcasselsND** [comment]
Using `ReadableStream`, it should only be a few pages of code to stream data from S3, using the `range` parameter to the AWS S3 `getObject` API https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property

https://developer.mozilla.org/en-US/docs/Web/API/Streams_API

**Comment by bcasselsND** [comment]
To expand on this a little more, my searches earlier in the summer found lots of streams built on node, so they would run on the server. But there were not streams that would work in Javascript the browser. For example, the AWS `createReadStream` [method looks ideal](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#createReadStream-property), but it is not supported in the browser.  This doc:  https://developer.mozilla.org/en-US/docs/Web/API/Streams_API  implies that the Streams interface is the only way to get streams in the browser. So it appears that we have to use something based on `ReadableStream`.

**Comment by calistenson** [comment]
After discussing with @vrajur-nd we're thinking the most reliable way to create our streaming would be to set up a foundation of flatbuffer files that is easy to parse. This is reasonably easy if we serialize them into a folder instead of one singular file and then load them file by file as we are streaming.
