### ISSUE TITLE
Pass Validity information in Lambda script

### ISSUE THREAD

**Issue by arjunskND** [NextDroid/potree#300]
We've talked about this. But with the lane schema changing, the lambda script does need this new field.

**Comment by jterranovaND** [comment]
@arjunskND , for reference, which field is this? 

Is it the fields `leftPointAnnotationStatus` and `leftPointAnnotationStatus` that were left out of the Lambda version?

**Comment by arjunskND** [comment]
No Jack, you can refer to this PR: https://github.com/NextDroid/DataSchemas/pull/39

Basically `leftPointAnomaly` and `rightPointAnomaly` are new additions to the schema.
