### ISSUE TITLE
Lat/Lon need to be constrained to x digits after the decimal

### ISSUE THREAD

**Issue by jstrinkaND** [NextDroid/potree#347]
saying that something is at 

latitude	42.48505783081055
longitude	-83.083862304687

in our visualizer is nonsense. That is sub-mm size. 

Please figure out the appropriate number of digits, then show the appropriate numbers.

**Comment by dgandhiAM** [comment]
@corylangenbachND Need to figure out what approach to take to determine the number of digits

**Comment by bcasselsND** [comment]
7 decimal places gives just over 1cm resolution.
```
julia> earthRadius = 6.371e6
6.371e6

julia> earthDiameter = earthRadius * 2pi
4.003017359204114e7

julia> cm = .01
0.01

julia> cmFraction = cm / earthDiameter
2.498115571996474e-10

julia> cmFraction * 360
8.993216059187307e-8
```

**Comment by bcasselsND** [comment]
@jallen-NextDroid Please show @elmassihgND where the latitude and longitude are shown. @elmassihgND I suggest you use `.toFixed(7)` to print these out.

**Comment by jallen-NextDroid** [comment]
@elmassihgND They're shown in `src/viewer/PropertyPanels/MeasurePanel.js`. The function is `createAttributesTable` To see the longitude/latitude in potree, you can place a measurement point (under Tools -> Measurements in the sidebar). Then scroll down in the sidebar and information is show for that point under Properties.
