### ISSUE TITLE
Where is the cartesian grid placed?

### ISSUE THREAD

**Issue by arjunskND** [NextDroid/potree#348]
![image (85).png](https://images.zenhubusercontent.com/5d234e28f9953d5554536e4e/3f86efa7-3dbf-4c96-9c53-f4d36e304375)

Where is the grid located? It should be `(rt_x, rt_y, rt_z - rtk_height)`. `rtk_height` should be coming from the `metadata_processing.json`

**Comment by dgandhiAM** [comment]
@jallen-NextDroid If you find we aren't using the `rtk_height` value, then incorporate it.

**Comment by arjunskND** [comment]
You just may wanna check if the `rtk_height` is applied in the local vehicle z. And you could use SATA2, between `t=270-300s`.
