### ISSUE TITLE
Disable annotation mode overlays when not in lane annotation mode

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#56]
Pressing 'a', 's', 'shift' in potree creates overlays that are only relevant in lane annotation mode --> disable these when not in lane annotation mode

**Comment by calistenson** [comment]
Remove "download lanes" button when you're not in annotation mode

**Comment by calistenson** [comment]
I'm not sure whether it makes sense or not to keep the car in the same spot when switching between modes or if it makes more sense to completely refresh to the beginning of the playbar. May see what @dgandhiAM thinks.

**Comment by calistenson** [comment]
Things kinda freeze up when you switch modes as the dataset is playing. I may disable the button unless the playbar is paused and force people to switch modes when the car is still.

**Comment by calistenson** [comment]
Other than these small things I'd consider permissioning this to only developers and feel comfortable merging it in!

**Comment by dgandhiAM** [comment]
> 
> 
> I'm not sure whether it makes sense or not to keep the car in the same spot when switching between modes or if it makes more sense to completely refresh to the beginning of the playbar. May see what @dgandhiAM thinks.

@calistenson Preferable to keep the car/time slider in the same spot, so a user can fix things as they go, i.e. run through the data in "analyze mode", notice a discrepancy, fix it in "annotate mode", and then resume in "analyze mode". I also haven't seen it, so let me know if I'm not quite "getting it" in terms of the UI.

**Comment by vrajur-nd** [comment]
Based on above comments:
 - [x] Disable download lanes button and put behind some kind of flag 
 - [x] Pause animation when switching modes

 TODO:
 - Think about a better way of limiting client access to truth data (introduced by download lanes button)

**Comment by vrajur-nd** [comment]
Complete
