### ISSUE TITLE
Add ability to type in timestamp to jump to

### ISSUE THREAD

**Issue by dgandhiAM** [NextDroid/potree#60]
Especially when referring to a list of issues, clients would like to be able to jump to the correct timestamp rather than having to drag the time slider.

**Comment by vrajur-nd** [comment]
Implemented in the branch `feature/time-input`.

##### Instructions for jumping to time
 - click time display (shown in screenshot below)
 - type desired time to jump to (time will be clamped between 0 and length of run in seconds) 
 - press enter to execute the jump

![image.png](https://images.zenhubusercontent.com/5aa183ef4b5806bc2bca0c77/a0423855-8eaa-4209-82f5-a432f43f291e)

**Comment by vrajur-nd** [comment]
Complete
