### ISSUE TITLE
B-spline Annotation Tool

### ISSUE THREAD

**Issue by dgandhiAM** [NextDroid/potree#89]
Problem:
The current annotation tool (with the ability to add/remove lane points) does a good job of handling straight road segments.  However, it remains tedious to correct points on curves.

Proposal:
It would be beneficial for the annotation mode to enable users to change an individual line segment into a B-spline for the purpose of designating the lane boundary on a curve (i.e. insert knots instead of new polyline points).  To maintain compatibility with the rest of the system, the B-spline knots need not be retained, as the spline can simply be interpolated back to a discrete polyline points during serialization with (RDP for reduction is optional).

Here's a javascript-based demo: http://jsxgraph.uni-bayreuth.de/wiki/index.php/B-splines

**Comment by dgandhiAM** [comment]
@arjunskND Here's the issue we were talking about.

**Comment by arjunskND** [comment]
@dgandhiAM , is this still relevant, given that we are moving to width based annotation?

**Comment by dgandhiAM** [comment]
@arjunskND Let's discuss at the next lane rep meeting

**Comment by jallen-NextDroid** [comment]
Closing, no longer relevant with opendrive
