### ISSUE TITLE
Increase Security of Visualization

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#9]
There are several steps we can/need to take to protect our visualization IP including code obfuscation and updating our security settings on the deployment server.

To Do:
- [ ] Compile all source code into a single file (e.g. using gulp uglify)
- [x] Remove all copyright/potree references from sidebar (replace with NextDroid logo?)
- [ ] Do not reveal source code directories to client
- [ ] Only a single html page should be accessible by client (or maybe two, one for full viz, one for streaming)

**Comment by calistenson** [comment]
These suggestions seem like good ideas and fairly pressing to solve to me. Have we made any progress here? I'd be happy to find a way to accomplish some of this. @vrajur-nd.

**Comment by vrajur-nd** [comment]
Initial work towards the second bullet point (copyright/potree references) has been done. A lot of these issues though conflict with the way potree is designed to run (i.e. everything is done client-side as opposed to server-side). None of us (Bob, Dan, myself) had too much experience with this last time we discussed this, so if you have suggestions/ideas that would be helpful. I think the first bullet (uglify) is a fairly quick piece to set up.
